version: "3.9"
services:
  postgres:
    container_name: postgres-payment
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "123123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "paymentdb"
    ports:
      - "0.0.0.0:5435:5432" # Bind to all interfaces on the host
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: pgadmin4-payment
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@db.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_LISTEN_PORT: "80"
    ports:
      - "0.0.0.0:16546:80" # Bind to all interfaces on the host
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge